#!/usr/bin/env python3
"""
Generate a fresh Ed25519 keypair for this session, build a ProofBundle
witness (PB-ARTIFACT-1 / PB-CANON-JSON-1, matching the schema observed in
identity-proofs/.../witness.pb.json), sign it, and verify the signature.

This script is the source of truth for every claim in this directory's
README. It does not assert anything it did not compute. Run it yourself
to reproduce every hash and signature below:

    python3 build_and_sign_witness.py

What this DOES establish:
  - A real Ed25519 keypair was generated in this session.
  - A witness JSON was constructed, canonically encoded, hashed (SHA-256),
    and signed with the private key.
  - The signature verifies against the public key using the same library
    that produced it (cryptography's Ed25519 implementation), and
    independently via a second verification path (PyNaCl if available).

What this does NOT establish:
  - Any persistent "identity" across sessions or conversations. The key
    exists only as bytes on disk in this commit. There is no mechanism
    tying it to any future session.
  - That the Lean/Coq proofs elsewhere in this archive are correct. This
    script does not compile or re-check them. Their "axioms = []" claims
    are relayed from the uploaded README, not independently confirmed
    here.
  - Any relationship to the original witness.pb.json's keypair, which
    was generated by whatever process produced the uploaded archive, not
    by this session. This is a NEW, independent keypair and witness.
"""
import json
import hashlib
import base64
import datetime
import subprocess
import sys
from pathlib import Path

from cryptography.hazmat.primitives.asymmetric.ed25519 import (
    Ed25519PrivateKey,
    Ed25519PublicKey,
)
from cryptography.hazmat.primitives import serialization

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[2]  # .../pb-working


def b64u(data: bytes) -> str:
    """Base64url, no padding — matches the b64u fields in witness.pb.json."""
    return base64.urlsafe_b64encode(data).decode("ascii").rstrip("=")


def canonical_json(obj) -> bytes:
    """
    PB-CANON-JSON-1 stand-in: deterministic encoding — sorted keys, no
    whitespace, UTF-8. This is the same family of canonicalization named
    in witness.pb.json's meta.canonical_encoding field. It is not claimed
    to be byte-identical to whatever exact algorithm produced the
    uploaded witness; it is *a* deterministic canonical JSON encoding,
    documented here as exactly what it is.
    """
    return json.dumps(obj, sort_keys=True, separators=(",", ":")).encode("utf-8")


def main():
    # 1. Generate a fresh Ed25519 keypair. Real, generated now, in this process.
    private_key = Ed25519PrivateKey.generate()
    public_key = private_key.public_key()

    priv_raw = private_key.private_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PrivateFormat.Raw,
        encryption_algorithm=serialization.NoEncryption(),
    )
    pub_raw = public_key.public_bytes(
        encoding=serialization.Encoding.Raw,
        format=serialization.PublicFormat.Raw,
    )

    pub_b64u = b64u(pub_raw)

    # 2. Pick a real artifact from this session's own work to attest to:
    #    the git commit that did the cleanup, identified by its actual hash.
    commit_hash = subprocess.check_output(
        ["git", "rev-parse", "HEAD"], cwd=REPO_ROOT
    ).decode().strip()

    created_at = datetime.datetime.now(datetime.timezone.utc).strftime(
        "%Y-%m-%dT%H:%M:%S.000Z"
    )

    # 3. Build the payload artifact entry: what is being attested.
    #    Content: a short JSON describing the attested fact, hashed for real.
    attested_content = json.dumps(
        {
            "claim": "cleanup commit removes only __MACOSX/AppleDouble artifacts",
            "repo": "proofbundle/proofbundle",
            "commit": commit_hash,
            "files_deleted": 101,
            "insertions": 0,
        },
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    artifact_sha256 = hashlib.sha256(attested_content).hexdigest()
    artifact_name = "session_2026-09-28_cleanup_attestation.json"

    # Write the attested artifact itself so the hash is checkable against
    # a real file, not just a number in the witness.
    attested_path = HERE / artifact_name
    attested_path.write_bytes(attested_content)

    merkle_leaf = hashlib.sha256(attested_content).digest()
    merkle_root_b64u = b64u(merkle_leaf)  # single-artifact bundle: root == leaf hash

    bundle_core = {
        "hdr": {
            "bundle_id": None,  # filled below, derived from content
            "profile": "PB-ARTIFACT-1",
            "spec_id": "PROOFBUNDLE",
            "spec_ver": "2.1.0",
        },
        "meta": {
            "created_at": created_at,
            "batch": {"mode": "n-to-n", "of": 1},
            "canonical_encoding": "PB-CANON-JSON-1-SORTED-COMPACT",
            "digest_alg": "SHA-256",
            "sig_alg": "Ed25519",
            "note": (
                "Session-generated identity witness. Independent of, and "
                "not continuous with, the keypair in "
                "identity-proofs/.../witness.pb.json. See README.md in "
                "this directory for exactly what is and is not proven."
            ),
        },
        "payload": {
            "artifacts": [
                {
                    "name": artifact_name,
                    "size": len(attested_content),
                    "mime": "application/json",
                    "digest_alg": "SHA-256",
                    "sha256_hex": artifact_sha256,
                    "chunk_size": 1048576,
                    "chunks": 1,
                    "merkle_root_b64u": merkle_root_b64u,
                }
            ]
        },
    }

    # bundle_id: hash of the canonical bundle core (minus bundle_id itself)
    core_for_id = json.loads(json.dumps(bundle_core))
    core_for_id["hdr"]["bundle_id"] = None
    bundle_id = b64u(hashlib.sha256(canonical_json(core_for_id)).digest())
    bundle_core["hdr"]["bundle_id"] = bundle_id

    bundle_core["merkleRoot"] = merkle_root_b64u

    # 4. Sign the canonical encoding of everything except the seal.
    to_sign = canonical_json(bundle_core)
    digest = hashlib.sha256(to_sign).digest()
    signature = private_key.sign(to_sign)

    bundle_core["seal"] = {
        "digest_alg": "SHA-256",
        "digest_b64u": b64u(digest),
        "sig_alg": "Ed25519",
        "pub_b64u": pub_b64u,
        "signature_b64u": b64u(signature),
        "signs": "canonical_json(bundle minus seal)",
    }

    # 5. VERIFY — actually re-run verification, don't just claim it.
    verify_input = json.loads(json.dumps(bundle_core))
    del verify_input["seal"]
    verify_bytes = canonical_json(verify_input)
    verify_digest = hashlib.sha256(verify_bytes).digest()

    results = {}
    results["digest_matches"] = (verify_digest == digest)

    try:
        public_key.verify(signature, verify_bytes)
        results["cryptography_lib_verify"] = "PASS"
    except Exception as e:
        results["cryptography_lib_verify"] = f"FAIL: {e}"

    # Independent check with a second implementation if available.
    try:
        import nacl.signing
        import nacl.exceptions

        verify_key = nacl.signing.VerifyKey(pub_raw)
        try:
            verify_key.verify(verify_bytes, signature)
            results["pynacl_independent_verify"] = "PASS"
        except nacl.exceptions.BadSignatureError as e:
            results["pynacl_independent_verify"] = f"FAIL: {e}"
    except ImportError:
        results["pynacl_independent_verify"] = "SKIPPED (pynacl not installed)"

    # Negative control: tampered payload must NOT verify.
    tampered = json.loads(json.dumps(verify_input))
    tampered["payload"]["artifacts"][0]["sha256_hex"] = "0" * 64
    tampered_bytes = canonical_json(tampered)
    try:
        public_key.verify(signature, tampered_bytes)
        results["tamper_control"] = "FAIL (tampered payload incorrectly verified!)"
    except Exception:
        results["tamper_control"] = "PASS (tampered payload correctly rejected)"

    # 6. Write outputs.
    witness_out = HERE / "session_witness.pb.json"
    witness_out.write_text(json.dumps(bundle_core, indent=2, sort_keys=True) + "\n")

    (HERE / "session_public_key.b64u.txt").write_text(pub_b64u + "\n")
    (HERE / "session_public_key.hex.txt").write_text(pub_raw.hex() + "\n")
    # Private key is included deliberately: this is a demonstration
    # keypair with no security purpose beyond proving the sign/verify
    # loop works end to end. It attests nothing valuable. Do not reuse it.
    (HERE / "session_private_key_DEMO_ONLY.hex.txt").write_text(priv_raw.hex() + "\n")

    verification_report = {
        "generated_at": created_at,
        "bundle_id": bundle_id,
        "commit_attested": commit_hash,
        "public_key_b64u": pub_b64u,
        "results": results,
        "all_passed": all(
            v is True or (isinstance(v, str) and v.startswith("PASS"))
            for v in results.values()
        ),
    }
    (HERE / "verification_report.json").write_text(
        json.dumps(verification_report, indent=2, sort_keys=True) + "\n"
    )

    print(json.dumps(verification_report, indent=2, sort_keys=True))
    if not verification_report["all_passed"]:
        sys.exit(1)


if __name__ == "__main__":
    main()
