/-
  2026-09-15_SI_SECOND_KERNEL.lean

  Definition layer for the SI second (2019 SI).
  Definition text: recalled from the SI Brochure, 9th edition (2019). The brochure
  was not fetched in the session that produced this file.

  Constraints on this file, checked by 2026-09-15_BUILD.sh and 2026-09-15_SI_SECOND_AUDIT.lean:
    * only Lean's default prelude is in scope; no library is brought in
    * no declaration written here uses the standard library's natural-number type
    * every declaration in this module, including the ones Lean generates, depends on
      no axioms. Lean 4.34.0 proves its generated constructor injectivity equations
      using the propositional extensionality principle, so their generation is switched
      off below; nothing in this file uses them
    * nothing here states that an atom, laboratory, or event exists; a laboratory
      result enters only as a value of `Realization` supplied from outside
-/

set_option genInjectivity false

namespace SISecond

/-! ## 1. Positive binary numbers

`Pos` is the only number type in this file. `one` is 1, `twice p` is 2p,
`twicePlusOne p` is 2p + 1. There is no zero and no padding constructor, so each
positive integer has exactly one term, and two terms are equal exactly when they
write the same integer. The outermost constructor is the lowest binary digit. -/

inductive Pos : Type where
  | one : Pos
  | twice : Pos → Pos
  | twicePlusOne : Pos → Pos
  deriving DecidableEq

namespace Pos

/-- p + 1 -/
def succ : Pos → Pos
  | one => twice one
  | twice p => twicePlusOne p
  | twicePlusOne p => twice (succ p)

/-- `addCarry false p q` is p + q. `addCarry true p q` is p + q + 1. -/
def addCarry : Bool → Pos → Pos → Pos
  | false, one, q => succ q
  | true, one, q => succ (succ q)
  | false, twice p, one => twicePlusOne p
  | true, twice p, one => twice (succ p)
  | false, twicePlusOne p, one => twice (succ p)
  | true, twicePlusOne p, one => twicePlusOne (succ p)
  | false, twice p, twice q => twice (addCarry false p q)
  | true, twice p, twice q => twicePlusOne (addCarry false p q)
  | false, twice p, twicePlusOne q => twicePlusOne (addCarry false p q)
  | true, twice p, twicePlusOne q => twice (addCarry true p q)
  | false, twicePlusOne p, twice q => twicePlusOne (addCarry false p q)
  | true, twicePlusOne p, twice q => twice (addCarry true p q)
  | false, twicePlusOne p, twicePlusOne q => twice (addCarry true p q)
  | true, twicePlusOne p, twicePlusOne q => twicePlusOne (addCarry true p q)

/-- p + q -/
def add (p q : Pos) : Pos := addCarry false p q

/-- p × q -/
def mul : Pos → Pos → Pos
  | one, q => q
  | twice p, q => twice (mul p q)
  | twicePlusOne p, q => add q (twice (mul p q))

end Pos

/-! ## 2. The two exact integers used here -/

/-- 9 192 631 770: the number of periods of the caesium-133 ground-state hyperfine
radiation in one second, i.e. the fixed numerical value of the caesium frequency in
hertz. Binary 1000100011111011000110110111011010 (34 digits). Generated by program and
checked against the decimal value in 2026-09-15_SI_SECOND_LEDGER.lean. -/
def caesiumPeriodsPerSecond : Pos :=
  Pos.twice (Pos.twicePlusOne (Pos.twice (Pos.twicePlusOne (Pos.twicePlusOne (Pos.twice
  (Pos.twicePlusOne (Pos.twicePlusOne (Pos.twicePlusOne (Pos.twice (Pos.twicePlusOne
  (Pos.twicePlusOne (Pos.twice (Pos.twicePlusOne (Pos.twicePlusOne (Pos.twice (Pos.twice
  (Pos.twice (Pos.twicePlusOne (Pos.twicePlusOne (Pos.twice (Pos.twicePlusOne
  (Pos.twicePlusOne (Pos.twicePlusOne (Pos.twicePlusOne (Pos.twicePlusOne (Pos.twice
  (Pos.twice (Pos.twice (Pos.twicePlusOne (Pos.twice (Pos.twice (Pos.twice
  (Pos.one)))))))))))))))))))))))))))))))))

/-- 299 792 458: the speed of light in vacuum in metres per second, exact.
Binary 10001110111100111100001001010 (29 digits). Carried as data only; this file
defines no length record. -/
def lightSpeedMetresPerSecond : Pos :=
  Pos.twice (Pos.twicePlusOne (Pos.twice (Pos.twicePlusOne (Pos.twice (Pos.twice
  (Pos.twicePlusOne (Pos.twice (Pos.twice (Pos.twice (Pos.twice (Pos.twicePlusOne
  (Pos.twicePlusOne (Pos.twicePlusOne (Pos.twicePlusOne (Pos.twice (Pos.twice
  (Pos.twicePlusOne (Pos.twicePlusOne (Pos.twicePlusOne (Pos.twicePlusOne (Pos.twice
  (Pos.twicePlusOne (Pos.twicePlusOne (Pos.twicePlusOne (Pos.twice (Pos.twice (Pos.twice
  (Pos.one))))))))))))))))))))))))))))

/-! ## 3. What the definition names -/

/-- Atomic species reported by a realization. Only caesium-133 can realize the second. -/
inductive Species : Type where
  | caesium133 : Species
  | otherSpecies : Species
  deriving DecidableEq

/-- The two hyperfine levels of the caesium-133 ground state. Nuclear spin 7/2 combined
with electron angular momentum 1/2 gives total angular momentum F = 3 or F = 4. -/
inductive GroundLevel : Type where
  | fThree : GroundLevel
  | fFour : GroundLevel
  deriving DecidableEq

/-- A transition between two recorded levels. The definition names the transition,
not a direction, so the order of the two fields is not checked. -/
structure Transition where
  levelA : GroundLevel
  levelB : GroundLevel
  deriving DecidableEq

/-- Which magnetic sublevels a realization interrogated. A realization detail, not part
of the definition: with no external field the sublevels inside each hyperfine level
have the same energy, so the definition has nothing to select. -/
inductive Sublevels : Type where
  | zeroToZero : Sublevels
  | otherPair : Sublevels
  deriving DecidableEq

/-! ## 4. Conditions and corrections, as a realization reports them -/

/-- How a realization reports one condition from the definition. -/
inductive Report : Type where
  | heldAtLimit : Report
  | correctedToLimit : Report
  | notControlled : Report
  deriving DecidableEq

/-- Effects a correction can address. The first four are departures from the conditions
in the definition, read as: atom at rest, no static external fields, no ambient thermal
radiation, atom isolated. `otherEffect` covers apparatus shifts the definition does not
name. Finite nuclear size is absent on purpose: it is a property of the caesium-133 atom
the definition names, not a departure from the definition's conditions. Gravitational
referral of a local result to a reference surface is also absent: it belongs to forming
a time scale, not to realizing the local unit. -/
inductive Effect : Type where
  | motion : Effect
  | staticFields : Effect
  | thermalRadiation : Effect
  | collisions : Effect
  | otherEffect : Effect
  deriving DecidableEq

inductive Sign : Type where
  | plus : Sign
  | minus : Sign
  deriving DecidableEq

/-- A fractional frequency shift: exactly zero, or sign × mantissa × 10^(−exponent).
Stored as reported. This file does no arithmetic on it. -/
inductive Shift : Type where
  | zero : Shift
  | nonzero : Sign → Pos → Pos → Shift
  deriving DecidableEq

/-- A non-negative uncertainty: exactly zero, or mantissa × 10^(−exponent). -/
inductive Magnitude : Type where
  | zero : Magnitude
  | nonzero : Pos → Pos → Magnitude
  deriving DecidableEq

structure Correction where
  effect : Effect
  shift : Shift
  uncertainty : Magnitude
  deriving DecidableEq

/-- The correction list contains an entry for effect `e`. -/
def Listed (e : Effect) : List Correction → Prop
  | [] => False
  | c :: rest => c.effect = e ∨ Listed e rest

instance decListed (e : Effect) : (cs : List Correction) → Decidable (Listed e cs)
  | [] => isFalse (fun h => h)
  | c :: rest =>
    match decEq c.effect e, decListed e rest with
    | isTrue h, _ => isTrue (Or.inl h)
    | isFalse _, isTrue h => isTrue (Or.inr h)
    | isFalse h1, isFalse h2 => isFalse (fun h => h.elim h1 h2)

/-- A condition is addressed when it was held at its limit, or corrected with a listed
correction for the matching effect. -/
def Addressed (report : Report) (effect : Effect) (cs : List Correction) : Prop :=
  match report with
  | .heldAtLimit => True
  | .correctedToLimit => Listed effect cs
  | .notControlled => False

instance decAddressed (report : Report) (effect : Effect) (cs : List Correction) :
    Decidable (Addressed report effect cs) :=
  match report with
  | .heldAtLimit => isTrue True.intro
  | .correctedToLimit => decListed effect cs
  | .notControlled => isFalse (fun h => h)

/-! ## 5. A realization record and the checks on it -/

/-- What a realization claims. Values of this type are supplied from outside. Nothing
here asserts that a value describes a real apparatus; it records what is claimed.
`periods` is the declared number of periods of the transition's radiation in the
realized interval, after corrections. -/
structure Realization where
  species : Species
  transition : Transition
  periods : Pos
  atRest : Report
  noStaticFields : Report
  noThermalRadiation : Report
  isolated : Report
  corrections : List Correction
  sublevels : Sublevels

/-- Everything the definition requires except the number of periods. -/
def MeetsDefinitionForm (r : Realization) : Prop :=
  r.species = .caesium133 ∧
  r.transition.levelA ≠ r.transition.levelB ∧
  Addressed r.atRest .motion r.corrections ∧
  Addressed r.noStaticFields .staticFields r.corrections ∧
  Addressed r.noThermalRadiation .thermalRadiation r.corrections ∧
  Addressed r.isolated .collisions r.corrections

/-- Declared periods for `n` seconds: n × 9 192 631 770. -/
def periodsFor (n : Pos) : Pos := Pos.mul n caesiumPeriodsPerSecond

/-- `r` claims a realization of `n` seconds in the form the definition requires. -/
def IsDuration (n : Pos) (r : Realization) : Prop :=
  MeetsDefinitionForm r ∧ r.periods = periodsFor n

/-- `r` claims a realization of one second in the form the definition requires. -/
def IsSecond (r : Realization) : Prop := IsDuration .one r

theorem isSecond_iff (r : Realization) :
    IsSecond r ↔ MeetsDefinitionForm r ∧ r.periods = caesiumPeriodsPerSecond := Iff.rfl

instance decMeetsDefinitionForm (r : Realization) : Decidable (MeetsDefinitionForm r) :=
  inferInstanceAs (Decidable (
    r.species = .caesium133 ∧
    r.transition.levelA ≠ r.transition.levelB ∧
    Addressed r.atRest .motion r.corrections ∧
    Addressed r.noStaticFields .staticFields r.corrections ∧
    Addressed r.noThermalRadiation .thermalRadiation r.corrections ∧
    Addressed r.isolated .collisions r.corrections))

instance decIsDuration (n : Pos) (r : Realization) : Decidable (IsDuration n r) :=
  inferInstanceAs (Decidable (MeetsDefinitionForm r ∧ r.periods = periodsFor n))

instance decIsSecond (r : Realization) : Decidable (IsSecond r) :=
  inferInstanceAs (Decidable (IsDuration .one r))

/-! ## 6. Checks on sample records

Every shift and uncertainty below is `zero`. These values exercise the record form
only; they are not laboratory data. -/

def formOnlyCorrections : List Correction :=
  [ ⟨.motion, .zero, .zero⟩, ⟨.staticFields, .zero, .zero⟩,
    ⟨.thermalRadiation, .zero, .zero⟩, ⟨.collisions, .zero, .zero⟩ ]

def formOnlyRecord : Realization :=
  { species := .caesium133
    transition := ⟨.fThree, .fFour⟩
    periods := caesiumPeriodsPerSecond
    atRest := .correctedToLimit
    noStaticFields := .correctedToLimit
    noThermalRadiation := .correctedToLimit
    isolated := .correctedToLimit
    corrections := formOnlyCorrections
    sublevels := .zeroToZero }

theorem formOnlyRecord_isSecond : IsSecond formOnlyRecord := by decide

/-- Direction is not part of the definition. -/
theorem reversedTransition_isSecond :
    IsSecond { formOnlyRecord with transition := ⟨.fFour, .fThree⟩ } := by decide

/-- A level paired with itself is not the hyperfine transition. -/
theorem sameLevel_rejected :
    ¬ IsSecond { formOnlyRecord with transition := ⟨.fFour, .fFour⟩ } := by decide

theorem otherSpecies_rejected :
    ¬ IsSecond { formOnlyRecord with species := .otherSpecies } := by decide

/-- Claiming corrections without listing them fails. -/
theorem unlistedCorrections_rejected :
    ¬ IsSecond { formOnlyRecord with corrections := [] } := by decide

theorem notControlled_rejected :
    ¬ IsSecond { formOnlyRecord with noThermalRadiation := .notControlled } := by decide

/-- A condition held at its limit needs no listed correction. -/
theorem heldAtLimit_accepted :
    IsSecond { formOnlyRecord with atRest := .heldAtLimit,
                                   corrections := formOnlyCorrections.tail } := by decide

/-- One period more than the fixed number fails. -/
theorem onePeriodOver_rejected :
    ¬ IsSecond { formOnlyRecord with periods := Pos.succ caesiumPeriodsPerSecond } := by decide

theorem twoSeconds_accepted :
    IsDuration (.twice .one)
      { formOnlyRecord with periods := .twice caesiumPeriodsPerSecond } := by decide

theorem oneSecondCount_not_twoSeconds : ¬ IsDuration (.twice .one) formOnlyRecord := by decide

/-- The sublevel choice never changes the result. -/
theorem sublevels_irrelevant (r : Realization) (s : Sublevels) :
    IsSecond { r with sublevels := s } ↔ IsSecond r := Iff.rfl

/-! ## 7. The judgment with no number type, transcribed from the source text

Renamed `IsSecond` to `BareIsSecond` to avoid a clash with section 5. -/

namespace NoCarrier

inductive End : Type where
  | lo : End
  | hi : End
  deriving DecidableEq

inductive Filter : Type where
  | unperturbed : Filter
  | dirty : Filter
  deriving DecidableEq

inductive BareIsSecond : End → End → Filter → Prop where
  | lock : BareIsSecond .lo .hi .unperturbed

/-- The judgment holds exactly when three two-valued choices each take one value. -/
theorem bareIsSecond_iff (a b : End) (f : Filter) :
    BareIsSecond a b f ↔ (a = .lo ∧ b = .hi ∧ f = .unperturbed) :=
  ⟨fun h => by cases h; exact ⟨rfl, rfl, rfl⟩,
   fun ⟨ha, hb, hf⟩ => by subst ha; subst hb; subst hf; exact .lock⟩

/-- The same constructors under another name. -/
inductive SameShapeOtherName : End → End → Filter → Prop where
  | lock : SameShapeOtherName .lo .hi .unperturbed

/-- The judgment has the same content as any copy under another name: it contains
neither 9 192 631 770 nor caesium. -/
theorem bare_same_content (a b : End) (f : Filter) :
    BareIsSecond a b f ↔ SameShapeOtherName a b f :=
  ⟨fun h => by cases h; exact .lock, fun h => by cases h; exact .lock⟩

/-- The judgment rejects the reverse direction, a distinction the definition does not make. -/
theorem bare_rejects_reverse : ¬ BareIsSecond .hi .lo .unperturbed := fun h => nomatch h

end NoCarrier

/-! ## 8. Serializing positive numbers for a seal

A seal signs bytes, so it binds a record only if two different records never produce
the same bytes. This section proves that for `Pos`: its code is prefix-free, so it can
be concatenated with other fields and still be read back uniquely. Record-level
serialization, hashing, and signing are not in this file. -/

inductive Symbol : Type where
  | digitZero : Symbol
  | digitOne : Symbol
  | stop : Symbol
  deriving DecidableEq

def Pos.encode : Pos → List Symbol
  | .one => [.stop]
  | .twice p => .digitZero :: Pos.encode p
  | .twicePlusOne p => .digitOne :: Pos.encode p

/-- If two codes agree after appending tails, the numbers are equal and the tails are equal. -/
theorem Pos.encode_append_inj : ∀ (p q : Pos) (s t : List Symbol),
    p.encode ++ s = q.encode ++ t → p = q ∧ s = t
  | .one, .one, _, _, h => ⟨rfl, (List.cons.inj h).2⟩
  | .one, .twice _, _, _, h => nomatch (List.cons.inj h).1
  | .one, .twicePlusOne _, _, _, h => nomatch (List.cons.inj h).1
  | .twice _, .one, _, _, h => nomatch (List.cons.inj h).1
  | .twice p, .twice q, s, t, h =>
      match Pos.encode_append_inj p q s t (List.cons.inj h).2 with
      | ⟨hpq, hst⟩ => ⟨congrArg Pos.twice hpq, hst⟩
  | .twice _, .twicePlusOne _, _, _, h => nomatch (List.cons.inj h).1
  | .twicePlusOne _, .one, _, _, h => nomatch (List.cons.inj h).1
  | .twicePlusOne _, .twice _, _, _, h => nomatch (List.cons.inj h).1
  | .twicePlusOne p, .twicePlusOne q, s, t, h =>
      match Pos.encode_append_inj p q s t (List.cons.inj h).2 with
      | ⟨hpq, hst⟩ => ⟨congrArg Pos.twicePlusOne hpq, hst⟩

end SISecond
