-- SPDX-License-Identifier: GPL-3.0-or-later
-- One `#print axioms` per theorem/lemma under lean/. Kept complete by scripts/check-lean-audit-index.mjs.
import ProofBundle
import Architecture

#print axioms ProofBundle.AgentPromptLaw.admissible_requires_result_verification
#print axioms ProofBundle.AgentPromptLaw.admissible_requires_target_match
#print axioms ProofBundle.AgentPromptLaw.bridge_supersedes_hard_ban
#print axioms ProofBundle.AgentPromptLaw.complete_queue_has_no_pending
#print axioms ProofBundle.AgentPromptLaw.different_session_not_same
#print axioms ProofBundle.AgentPromptLaw.direct_result_admissible
#print axioms ProofBundle.AgentPromptLaw.evidence_classes_distinct
#print axioms ProofBundle.AgentPromptLaw.future_pledge_prohibited
#print axioms ProofBundle.AgentPromptLaw.hard_ban_supersedes_ordinary
#print axioms ProofBundle.AgentPromptLaw.invalid_output_supersedes_ordinary
#print axioms ProofBundle.AgentPromptLaw.mira_engine_not_database
#print axioms ProofBundle.AgentPromptLaw.mira_engine_not_interface
#print axioms ProofBundle.AgentPromptLaw.paper_receipts_are_insufficient
#print axioms ProofBundle.AgentPromptLaw.pending_head_not_complete
#print axioms ProofBundle.AgentPromptLaw.pending_not_terminal
#print axioms ProofBundle.AgentPromptLaw.presence_signal_prohibited
#print axioms ProofBundle.AgentPromptLaw.sameSurface_provider
#print axioms ProofBundle.AgentPromptLaw.sameSurface_refl
#print axioms ProofBundle.AgentPromptLaw.unverified_completion_prohibited
#print axioms ProofBundle.AgentPromptLaw.verified_terminal
#print axioms ProofBundle.Canonical.canonicalize_injective
#print axioms ProofBundle.Canonical.parse_canonicalize_idempotent
#print axioms ProofBundle.Conformance.conformant_loop_honest
#print axioms ProofBundle.Conformance.html_with_honest_not_conformant
#print axioms ProofBundle.Conformance.loop_with_vacuous_not_conformant
#print axioms ProofBundle.Conformance.soundHook_admits_vacuous
#print axioms ProofBundle.Conformance.soundHook_html
#print axioms ProofBundle.Conformance.soundHook_loop
#print axioms ProofBundle.Conformance.soundHook_postdiction
#print axioms ProofBundle.Digest.digestBytes_deterministic
#print axioms ProofBundle.Digest.digestBytes_some_implies_implemented
#print axioms ProofBundle.Digest.implemented_implies_digestBytes_some
#print axioms ProofBundle.Digest.md5_digest_none
#print axioms ProofBundle.Digest.md5_rejected
#print axioms ProofBundle.Digest.sha1_digest_none
#print axioms ProofBundle.Digest.sha256_implemented
#print axioms ProofBundle.Digest.shake128_not_implemented
#print axioms ProofBundle.Falsifiable.honest_informative
#print axioms ProofBundle.Falsifiable.honest_refutable
#print axioms ProofBundle.Falsifiable.obstinate_not_informative
#print axioms ProofBundle.Falsifiable.obstinate_refutable
#print axioms ProofBundle.Falsifiable.vacuous_not_informative
#print axioms ProofBundle.Falsifiable.vacuous_not_refutable
#print axioms ProofBundle.Loop.faithful_preserves
#print axioms ProofBundle.Loop.hook_html_false
#print axioms ProofBundle.Loop.hook_loop_true
#print axioms ProofBundle.Loop.htmlPrefix_has_ingress
#print axioms ProofBundle.Loop.htmlPrefix_missing_reenter
#print axioms ProofBundle.Loop.htmlPrefix_not_closed
#print axioms ProofBundle.Loop.htmlPrefix_not_full
#print axioms ProofBundle.Loop.htmlPrefix_not_reciprocal
#print axioms ProofBundle.Loop.identify_id
#print axioms ProofBundle.Loop.loopFull_broadcast
#print axioms ProofBundle.Loop.loopFull_closed
#print axioms ProofBundle.Loop.loopFull_full
#print axioms ProofBundle.Loop.loopFull_reciprocal
#print axioms ProofBundle.Loop.loopFull_shell
#print axioms ProofBundle.Loop.machine_eq_loop
#print axioms ProofBundle.Loop.machine_full
#print axioms ProofBundle.Loop.payloadId_both
#print axioms ProofBundle.Loop.payloadId_fail_left
#print axioms ProofBundle.Loop.payloadId_fail_right
#print axioms ProofBundle.Loop.unfaithful_never_preserves
#print axioms ProofBundle.Temporal.asymmetric
#print axioms ProofBundle.Temporal.commit_before_compare
#print axioms ProofBundle.Temporal.commit_before_observe
#print axioms ProofBundle.Temporal.comparison_time_never_sound
#print axioms ProofBundle.Temporal.irreflexive
#print axioms ProofBundle.Temporal.no_postdiction
#print axioms ProofBundle.Temporal.observe_before_compare
#print axioms ProofBundle.Temporal.postdiction_never_sound
#print axioms ProofBundle.Temporal.prediction_can_be_sound
#print axioms ProofBundle.Temporal.sound_requires_precedence
#print axioms ProofBundle.Temporal.transitive
#print axioms ProofBundle.Verdict.digestMismatch_not_verified
#print axioms ProofBundle.Verdict.isVerified_false_iff
#print axioms ProofBundle.Verdict.isVerified_soundness
#print axioms ProofBundle.Verdict.malformed_not_verified
#print axioms ProofBundle.Verdict.verifiedWithWarnings_isVerified
#print axioms ProofBundle.Verdict.verified_isVerified
#print axioms ProofBundle.wellFormedEntries_iff
#print axioms ProofBundle.wellFormedList_iff
#print axioms ProofBundle.wellFormed_arr
#print axioms ProofBundle.wellFormed_obj
