import { strict as assert } from 'node:assert';
import { mkdtemp, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomBytes } from 'node:crypto';
import { execFile as execFileCallback } from 'node:child_process';
import { promisify } from 'node:util';
import { mlkemKeygen } from './mlkem.mjs';
import { encryptRange, encryptReadable, decryptVaultBytes, RECORD_TYPES, VAULT_PROFILE } from './vault-stream.mjs';
import { Readable } from 'node:stream';

const execFile = promisify(execFileCallback);

const dir = await mkdtemp(join(tmpdir(), 'pb-vault-test-'));
const source = join(dir, 'source.bin'), output = join(dir, 'part.pbv');
const data = randomBytes(300_123); await writeFile(source, data);
const { encapsKey, decapsKey } = mlkemKeygen(randomBytes(64), 'ML-KEM-768');
const result = await encryptRange({ sourcePath: source, outputPath: output, recipientEncapsKey: encapsKey, offset: 17, length: 280_000, chunkBytes: 65_536, partIndex: 2, partCount: 4, archiveId: '00112233445566778899aabbccddeeff' });
assert.equal(result.header.profile, VAULT_PROFILE);
assert.equal(result.terminal.data_records, 5);
const opened = decryptVaultBytes(await readFile(output), decapsKey);
assert.deepEqual(opened.records.map(x => x.type), [RECORD_TYPES.metadata, RECORD_TYPES.data, RECORD_TYPES.data, RECORD_TYPES.data, RECORD_TYPES.data, RECORD_TYPES.data, RECORD_TYPES.final]);
assert.deepEqual(Buffer.concat(opened.records.filter(x => x.type === RECORD_TYPES.data).map(x => x.plaintext)), data.subarray(17, 280_017));
const terminal = JSON.parse(opened.records.at(-1).plaintext.toString('utf8'));
assert.equal(terminal.source_length, 280_000);
const tampered = Buffer.from(await readFile(output)); tampered[tampered.length - 20] ^= 1;
assert.throws(() => decryptVaultBytes(tampered, decapsKey));
const compressed = join(dir, 'compressed.pbv');
await encryptRange({ sourcePath: source, outputPath: compressed, recipientEncapsKey: encapsKey, offset: 100, length: 200_000, chunkBytes: 65_536, compression: 'zstd-3' });
const compressedOpened = decryptVaultBytes(await readFile(compressed), decapsKey);
const compressedBytes = Buffer.concat(compressedOpened.records.filter(x => x.type === RECORD_TYPES.data).map(x => x.plaintext));
await writeFile(join(dir, 'range.zst'), compressedBytes);
await execFile('zstd', ['-d', '-q', '-c', join(dir, 'range.zst')], { encoding: 'buffer', maxBuffer: 1_000_000 }).then(({ stdout }) => assert.deepEqual(stdout, data.subarray(100, 200_100)));
assert.equal(compressedOpened.header.compression, 'zstd-level-3-independent-range');
assert.ok(compressedBytes.length > 0);
const streamed = join(dir, 'streamed.pbv');
await encryptReadable({ readable: Readable.from([data.subarray(0, 12_345), data.subarray(12_345)]), outputPath: streamed, recipientEncapsKey: encapsKey, streamMetadata: { container: 'test' }, chunkBytes: 65_536 });
const streamOpened = decryptVaultBytes(await readFile(streamed), decapsKey);
assert.deepEqual(Buffer.concat(streamOpened.records.filter(x => x.type === RECORD_TYPES.data).map(x => x.plaintext)), data);
console.log('PB-VAULT-1: 11 assertions passed');
