// Integration tests: the CLI is driven as a real subprocess, so exit codes,
// stdout and file round-trips are exercised the way a caller sees them.
//
// The round-trip that matters most: a key generated by the CLI, used by the
// CLI to sign a file, must verify through the CLI — and the same signature
// must fail against a modified file with exit code 1, not 0.

import test from 'node:test';
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const CLI = new URL('../../bin/proofbundle.mjs', import.meta.url).pathname;

function run(args, { expectFailure = false } = {}) {
  try {
    const stdout = execFileSync(process.execPath, [CLI, ...args], { encoding: 'utf-8' });
    return { code: 0, stdout };
  } catch (e) {
    if (!expectFailure) throw new Error(`unexpected failure (${e.status}): ${e.stderr || e.stdout}`);
    return { code: e.status, stdout: e.stdout ?? '', stderr: e.stderr ?? '' };
  }
}

const work = mkdtempSync(join(tmpdir(), 'pb-cli-'));

test('version separates implementation version from format version', () => {
  const { stdout } = run(['version', '--json']);
  const v = JSON.parse(stdout);
  assert.equal(v.formatVersion, 'PB/v1');
  assert.ok(v.implementationVersion);
});

test('doctor reports available and unavailable providers with reasons', () => {
  const { stdout } = run(['doctor', '--json']);
  const d = JSON.parse(stdout);
  assert.ok(d.providersAvailable.includes('node:crypto'));
  assert.ok(d.providersUnavailable.length > 0);
  for (const u of d.providersUnavailable) assert.ok(u.reason.length > 0);
  assert.match(d.leanToolchain, /NOT INSTALLED/);
});

test('algorithms lists the registry and filters by status', () => {
  const all = JSON.parse(run(['algorithms', '--json']).stdout);
  assert.equal(all.length, 95);
  const complete = JSON.parse(run(['algorithms', '--json', '--status', 'COMPLETE']).stdout);
  assert.ok(complete.length > 0 && complete.length < all.length);
  assert.ok(complete.every((r) => r.status === 'COMPLETE'));
});

test('keygen then sign then verify round-trips through files', () => {
  const doc = join(work, 'doc.txt');
  writeFileSync(doc, 'provenance payload');
  run(['keygen', '--alg', 'Ed25519', '--out', join(work, 'key.json')]);
  const key = JSON.parse(readFileSync(join(work, 'key.json'), 'utf-8'));
  assert.equal(key.algorithm, 'Ed25519');
  assert.match(key.keyId, /^[0-9a-f]{64}$/);

  run(['sign', doc, '--key', join(work, 'key.json'), '--out', join(work, 'sig.json')]);
  const { stdout } = run(['verify', doc, '--signature', join(work, 'sig.json'), '--json']);
  const v = JSON.parse(stdout);
  assert.equal(v.verdict, 'VERIFIED');
  // The scope disclaimer is part of the output contract, not decoration.
  assert.match(v.scope, /does not establish that the signed statement is true/);
});

test('a modified file fails verification with exit code 1', () => {
  const doc = join(work, 'doc.txt');
  const tampered = join(work, 'tampered.txt');
  writeFileSync(doc, 'provenance payload');
  writeFileSync(tampered, 'provenance payloaD');
  run(['keygen', '--alg', 'Ed25519', '--out', join(work, 'k2.json')]);
  run(['sign', doc, '--key', join(work, 'k2.json'), '--out', join(work, 's2.json')]);
  const r = run(['verify', tampered, '--signature', join(work, 's2.json'), '--json'], { expectFailure: true });
  assert.equal(r.code, 1);
  assert.equal(JSON.parse(r.stdout).verdict, 'INVALID_SIGNATURE');
});

test('merkle build/prove/verify round-trips through files', () => {
  run(['merkle-build', 'a', 'b', 'c', 'd', 'e', '--out', join(work, 'tree.json')]);
  run(['merkle-prove', '--tree', join(work, 'tree.json'), '--index', '3', '--out', join(work, 'proof.json')]);
  const v = JSON.parse(run(['merkle-verify', '--proof', join(work, 'proof.json'), '--json']).stdout);
  assert.equal(v.verdict, 'VERIFIED');
  assert.equal(v.index, 3);
});

test('a merkle proof edited on disk fails verification with exit code 1', () => {
  run(['merkle-build', 'a', 'b', 'c', 'd', '--out', join(work, 't2.json')]);
  run(['merkle-prove', '--tree', join(work, 't2.json'), '--index', '1', '--out', join(work, 'p2.json')]);
  const proof = JSON.parse(readFileSync(join(work, 'p2.json'), 'utf-8'));
  proof.proof.index = 2;
  writeFileSync(join(work, 'p2.json'), JSON.stringify(proof));
  const r = run(['merkle-verify', '--proof', join(work, 'p2.json'), '--json'], { expectFailure: true });
  assert.equal(r.code, 1);
  assert.equal(JSON.parse(r.stdout).verdict, 'INVALID_SIGNATURE');
});

test('mmr append is incremental and proofs verify against the current root', () => {
  run(['mmr-append', 'x', 'y', 'z', '--out', join(work, 'mmr.json')]);
  const after3 = JSON.parse(run(['mmr-append', 'w', '--state', join(work, 'mmr.json'), '--json']).stdout);
  assert.equal(after3.leafCount, 4);
  run(['mmr-prove', '--state', join(work, 'mmr.json'), '--index', '2', '--out', join(work, 'mp.json')]);
  assert.equal(JSON.parse(run(['mmr-verify', '--proof', join(work, 'mp.json'), '--json']).stdout).verdict, 'VERIFIED');
});

test('lineage create then verify accepts a DAG', () => {
  run(['lineage-create', 'source:A', 'derived:B:0', 'derived:C:0,1', '--out', join(work, 'lin.json')]);
  const v = JSON.parse(run(['lineage-verify', '--lineage', join(work, 'lin.json'), '--json']).stdout);
  assert.equal(v.verdict, 'VERIFIED');
  assert.equal(v.nodeCount, 3);
});

test('lineage verify reports a cycle injected into the file', () => {
  const cyclic = { nodes: [{ id: 'x', parents: ['y'] }, { id: 'y', parents: ['x'] }] };
  writeFileSync(join(work, 'cyc.json'), JSON.stringify(cyclic));
  const r = run(['lineage-verify', '--lineage', join(work, 'cyc.json'), '--json'], { expectFailure: true });
  assert.equal(r.code, 1);
  assert.equal(JSON.parse(r.stdout).verdict, 'LINEAGE_CYCLE');
});

test('generating a key for a verify-only algorithm is refused', () => {
  const r = run(['keygen', '--alg', 'RSA-PKCS1v1.5'], { expectFailure: true });
  assert.equal(r.code, 1);
  assert.match(r.stderr, /verify-only/);
});

test('an unimplemented but specified command exits 2 and says so', () => {
  const r = run(['encrypt'], { expectFailure: true });
  assert.equal(r.code, 2);
  assert.match(r.stderr, /NOT IMPLEMENTED/);
});

test('an unknown command exits 2', () => {
  const r = run(['not-a-command'], { expectFailure: true });
  assert.equal(r.code, 2);
  assert.match(r.stderr, /unknown command/);
});

test('--quiet suppresses stdout while preserving the exit code', () => {
  const doc = join(work, 'q.txt');
  writeFileSync(doc, 'x');
  run(['keygen', '--alg', 'Ed25519', '--out', join(work, 'qk.json'), '--quiet']);
  run(['sign', doc, '--key', join(work, 'qk.json'), '--out', join(work, 'qs.json'), '--quiet']);
  const r = run(['verify', doc, '--signature', join(work, 'qs.json'), '--quiet']);
  assert.equal(r.code, 0);
  assert.equal(r.stdout.trim(), '');
});

test('JSON output is stable across repeated runs', () => {
  const a = run(['algorithms', '--json', '--family', 'AEAD']).stdout;
  const b = run(['algorithms', '--json', '--family', 'AEAD']).stdout;
  assert.equal(a, b);
});
